### ISSUE TITLE
hey the from "discord.ext import commands from bot_logger import logger import json import logging" part, it says it doesnt know the discord.ext

### ISSUE THREAD

**Issue by Co2Pog** [kodycode/PokeBot-Python#10]

**Comment by kodycode** [comment]
Hi, as of two weeks ago, I'm re-writing the bot over in this branch [here](https://github.com/kodycode/PokeBot-Python/tree/v2_refactor). The codebase is very outdated and unusable but I'm thinking maybe by the end of this week or the next, I could get it all up-to-date and ironed out. I'll update the repository accordingly with updated instructions on how to run the bot and from there, this issue should be resolved.
