### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by wicedclown** [kodycode/PokeBot-Python#14]
when i set everything up i get this error
discord.ext.commands.bot: Ignoring exception in command None
so i need help plz

**Comment by wicedclown** [comment]
i cant use commands im not getting the error anymore but they dont do anything

**Comment by kodycode** [comment]
Hi, as of two weeks ago, I'm re-writing the bot over in this branch [here](https://github.com/kodycode/PokeBot-Python/tree/v2_refactor). The codebase is very outdated and unusable but I'm thinking maybe by the end of this week or the next, I could get it all up-to-date and ironed out. I'll update the repository accordingly once I'm finished.

**Comment by wicedclown** [comment]
When everything is updated its still using python right

**Comment by kodycode** [comment]
Yep, still using Python.

**Comment by wicedclown** [comment]
How long will it take to get it all done

**Comment by kodycode** [comment]
Thinking maybe by the end of this week, latest could be end of next week.

**Comment by wicedclown** [comment]
Sounds good can you reply to this when it's done and ready so i set mine up

**Comment by wicedclown** [comment]
Also is there a way to change legendary pokemon spawn rates and a way to have the bot tell you if you got a shiny

**Comment by kodycode** [comment]
> Also is there a way to change legendary pokemon spawn rates and a way to have the bot tell you if you got a shiny

For legendary spawn rates, not at the current moment but that can be an addition to think about the in future. As for getting a shiny, you can make a discord text channel called "shiny" and it'll post in there, but also as you capture pokemon - their respective shiny image should display.

Still cranking out the bot which will still take a while, but after fixing the catch command today, here's what it displays when you catch a shiny.

Catching a pokemon in regular text channel after issuing the command !catch:
<img width="270" alt="Screenshot 2023-01-25 at 2 54 33 AM" src="https://user-images.githubusercontent.com/13345899/214509077-c673078c-29c1-4de6-b6b0-aedd8383e19a.png">

In a text channel called "shiny", PokeBot gets automatically posted here (with gif image):
<img width="213" alt="Screenshot 2023-01-25 at 2 54 44 AM" src="https://user-images.githubusercontent.com/13345899/214509139-18c67f5e-b154-4bb5-807f-ccf1c9300959.png">

**Comment by wicedclown** [comment]
so in my discord if i make a channel called shiny it will automatically post in there when someone catches a shiny

**Comment by wicedclown** [comment]
please let me knowwhen its ready and also when it is ready how do i start the happy hour thing

**Comment by wicedclown** [comment]
any update?

**Comment by kodycode** [comment]
Still going at it.

**Comment by wicedclown** [comment]
So maybe sometime this week?

**Comment by kodycode** [comment]
Bot's now finished with the rework. There may be bugs I didn't catch as a result of the big effort in re-implementing everything, but post any new issues you find out. Please also read the [README.md](https://github.com/kodycode/PokeBot-Python/blob/main/README.md) file here on the bot status and for instructions. I've also updated the wiki to reflect the new changes as well.
