### ISSUE TITLE
I can't edit any of the files to put in the token how do I do that so I can add the bot?

### ISSUE THREAD

**Issue by ThiccTrap** [kodycode/PokeBot-Python#2]

**Comment by kodycode** [comment]
Rename `config_template.json` to `config.json` and insert your token between the quotes in the token field.

**Comment by ThiccTrap** [comment]
I've almost got it figured it...I think lol Python is just the confusing part but thank you for replying

**Comment by kodycode** [comment]
No problem! Let me know if you're still having issues.
