### ISSUE TITLE
How to gift

### ISSUE THREAD

**Issue by ThiccTrap** [kodycode/PokeBot-Python#3]
Hi I have the bot all set up and I'm just wondering how do I give a gift to someone and if anything needs to be put in the gift list

**Comment by kodycode** [comment]
To give out gifts, simply enter the values you want in the `config.json` like so:

```
"gift_list": {
    "pokemon": {
	"egg": 10,
	"egg-manaphy": 2,
	"coffee": 1
    },
    "lootbox": {
	"bronze": 1,
	"legendary": 3
	}
    },
```

And then just have the user type your bot's command prefix followed by the `gift` command.

I forgot to document how to add gifts so thanks for reminding me, but another thing to note is that the gift feature is also pretty open. You can pretty much add anything else as a pokemon, hence the `coffee` being there, so do take note as the feature doesn't do spell-checks for the pokemon that exists in the bot's dictionary.
