### ISSUE TITLE
cog error

### ISSUE THREAD

**Issue by sp-ytdl-core** [kodycode/PokeBot-Python#6]
Failed to load cog manager
ExtensionFailed: Extension 'cogs.cog_manager' raised an error: TypeError: cogs must derive from Cog
Failed to update game status. See error.log.

**Comment by kodycode** [comment]
Updated the bot to the latest discord API, let me know if that fixes things and also let me know if there are any other lingering errors.

**Comment by sp-ytdl-core** [comment]
hmm smh did it will work now?

**Comment by sp-ytdl-core** [comment]
it sends message that Trainer hasn't set off on his journey to catch 'em all yet.

**Comment by kodycode** [comment]
That means you have to catch a pokemon using the catch command first before using the other commands. I'll specify that in the error message later tonight when I have time to update it.
