### ISSUE TITLE
pokemon_functionality not working

### ISSUE THREAD

**Issue by digasred** [kodycode/PokeBot-Python#7]
i tried to everything i could i tried to change somethings but I cant figure it out

**Comment by digasred** [comment]
it only says : Failed to cache trainer object. See error.log.

**Comment by kodycode** [comment]
What does the error log say?

**Comment by digasred** [comment]
[10/03/2020 10:07:00 PM](pokemon_functionality.py) - ERROR - Exception: 'NoneType' object has no attribute 'change_presence'
[10/03/2020 10:15:20 PM](pokemon_functionality.py) - ERROR - Exception: 'NoneType' object has no attribute 'request'

**Comment by digasred** [comment]
its the all file not just a command thats not working. It gives me the same type of error

**Comment by kodycode** [comment]
Did you install discord.py?

**Comment by digasred** [comment]
yes

**Comment by kodycode** [comment]
Could you post the entire log file? It's hard to determine what's exactly the issue as it could be many different things in this context. That error shouldn't happen unless the discord library isn't installed properly.

**Comment by digasred** [comment]
never mind i fixed the error

**Comment by digasred** [comment]
it was not with your file it was with something I putted

**Comment by kodycode** [comment]
Alright, glad you managed to fix it.
