### ISSUE TITLE
Admin Cmds

### ISSUE THREAD

**Issue by MntRushmore** [kodycode/PokeBot-Python#9]
Can U Add A Cmd Where Admins Can Like Gift Gifts To Members? Or Give Out Tokens? @kodycode

**Comment by kodycode** [comment]
Hi, as of two weeks ago, I'm re-writing the bot over in this branch [here](https://github.com/kodycode/PokeBot-Python/tree/v2_refactor). The codebase is very outdated and unusable but I'm thinking maybe by the end of this week or the next, I could get it all up-to-date and ironed out. I'll update the repository accordingly once I'm finished.

As for additional commands/features, I'll take what you've said so far into consideration as well after the bot is functional again.
